GET  http://localhost:5001/users

###

POST  http://localhost:5001/users/register
Content-Type: application/json

{
    "name": "Nitish",
    "password": "password1"
}

### Login Authenticate

POST  http://localhost:5001/users/login
Content-Type: application/json

{
    "name": "Nitish",
    "password": "password1"
}